version: '3.9'

services:
#  fastapi:
#    build: .
#    working_dir: /development
#    ports:
#      - 8080:80
#    environment:
#      - DATABASE_USER=postgres
#      - DATABASE_HOST=db
#      - DATABASE_PASSWORD=example
#    volumes:
#      - .:/development
#    depends_on:
#      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
