name: Deploy to DEV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PULUMI_CONFIG_PASSPHRASE: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get commit hash
        id: get-commit-hash
        run: |
          commit-hash=$(git rev-parse --short HEAD)
          echo "commit-hash=$commit-hash" >> $GITHUB_OUTPUT

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: 'fastapi-prototype'
          IMAGE_TAG: "${{ steps.get-commit-hash.outputs.commit-hash }}-${{ steps.get-timestamp.outputs.timestamp }}"
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  

      - name: Install pulumi
        uses: pulumi/actions@v4
        with:
          pulumi-version: ^3.0.0

      - name: Install dependencies
        run: npm install
        working-directory: infra

      - name: Pulumi Login
        run: pulumi login s3://${{secrets.PULUMI_STATE_S3_BUCKET}}
        working-directory: infra

      - name: Select stack
        run: pulumi stack select dev
        working-directory: infra

      - name: Set up Pulumi Configs
        run: |
          pulumi config set image_tag "${{ steps.get-commit-hash.outputs.commit-hash }}"
          pulumi config set app_name "fastapi-prototype"
          pulumi config set credentials_secret "${{secrets.DB_CREDENTIALS_SECRET}}"
        working-directory: infra

      - name: Deploy Infrastructure Changes
        run: pulumi up --yes
        working-directory: infra
        env:
          DOCKER_HOST: 'tcp://127.0.0.1:2376/'
